#!/bin/bash

FILES=".gemrc
.irbrc
.vimrc
.gitconfig
"
DIRECTORY=$(cd `dirname $0` && pwd)

if [ $DIRECTORY != $HOME/.vim ]; then
  echo moving directory to .vim folder
  rm .vim -fr
  mv $DIRECTORY $HOME/.vim
  cd $HOME/.vim
fi

for f in $FILES; do
  if [ ! -e $HOME/$f ]; then
    echo adding link to $f
    ln -s $HOME/.vim/$f $HOME/$f
  else
    echo $f already exists in $HOME/$f
  fi
done

echo initalising git submodules
git submodule init
echo git submodules initalised

echo updating submodules
git submodule update
echo submodules updated

BASH_SOURCES="aliases
bash_customise
"
for f in $BASH_SOURCES; do
  if  ! grep -Fxq "source ~/.vim/$f" ~/.bashrc 
  then
    echo "source ~/.vim/$f" >> ~/.bashrc
  fi
done

echo install complete
